[package]
name = "beautifull_bridges"
version = "0.1.0"
authors = ["jdmejiav <jdmejiav@eafit.edu.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
